# Generated by Django 4.2.18 on 2025-02-02 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('special_finishes', models.TextField()),
                ('yarn_count', models.CharField(max_length=255)),
                ('moq', models.IntegerField()),
                ('mcq', models.IntegerField()),
                ('knitting_method', models.CharField(max_length=255)),
                ('print', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=255)),
                ('reorder_level', models.IntegerField()),
                ('lead_time', models.IntegerField()),
                ('item_color', models.CharField(max_length=255)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemcategory')),
            ],
            options={
                'db_table': 'stock_item',
            },
        ),
    ]
