# Generated by Django 4.2.18 on 2025-02-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('stock_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.stockitem')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'db_table': 'supplier_stock_item',
                'unique_together': {('supplier_id', 'stock_item_id')},
            },
        ),
    ]
