# Generated by Django 4.2.18 on 2025-02-02 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_supplierstockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualStock',
            fields=[
                ('virtual_stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markup_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_stock_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.supplierstockitem')),
            ],
            options={
                'db_table': 'virtual_stock',
            },
        ),
    ]
