# Generated by Django 4.2.18 on 2025-02-02 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('supplier_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'supplier_category',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('bank_details', models.TextField()),
                ('payment_terms', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('shipping_port', models.CharField(max_length=255)),
                ('shipping_terms', models.TextField()),
                ('certification', models.TextField()),
                ('brands_work_with', models.TextField()),
                ('supplier_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategory')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
